### ISSUE TITLE
Syntax Coloring submenu on Editing menu disappeared

### ISSUE THREAD

**Issue by Skippern** [omz/Dash-Plugin-for-Xcode#36] opened 2015-04-13 02:42 UTC
After installing this plugin, the Syntax Coloring submenu is empty. I work with several projects that have non-detecting filenames or languages, and are now no longer able to set language for syntax colouring.

**Comment by Kapeli** [comment] 2015-04-13 06:42
The "Syntax Coloring" menu is missing completely for me. Is it added by a different plugin maybe?

**Comment by Skippern** [comment] 2015-04-13 10:16
Syntax Coloring is default in the Editor menu, no plugins required.

**Comment by Kapeli** [comment] 2015-04-13 15:26
Ah, found it. It seems to work fine even with the Dash plugin.

Can you try to uninstall other plugins, maybe it's a compatibility issue with some other plugin?

Does it happen for any file you open? If not, can you send a sample project that you experience the issue with?

**Comment by Skippern** [comment] 2015-04-13 15:38
The only other plugin i have is VVDocumentation, and this plugin I have had for 2 years. This problem only occured after installing Dash. If it is a conflict with another plugin it is conflict between Dash and VVDocumentation

Aun Johnsen

**Comment by Kapeli** [comment] 2015-04-13 15:51
Please test if the problem goes away after you uninstall VVDocumentation.

**Comment by Skippern** [comment] 2015-04-13 16:50
Now I have uninstalled all plugins and extensions, and restarted Xcode, seems like something is stuck in memory. Only thing I haven’t done, but doubt will solve anything is restarting the computer

**Comment by Kapeli** [comment] 2015-04-13 19:44
If you remove the Dash plugin and the issue is still there, then it might be an issue with Xcode. Nothing in the Dash plugin persists after you remove it.

**Comment by Skippern** [comment] 2015-04-13 19:49
I have reported it to Apple Seeds Feedback (beta program feedback) as `#593153`, I forgot to mention that I run `OS X 10.10.3 beta` and `Xcode 6.3`, though I saw the menu disappear in `Xcode 6.2.2` under `OS X 10.10.2 beta build`. I have no computer running release OS X

**Comment by liuxuan30** [comment] 2015-04-14 03:10
I just uses VVDocumenter and Dash plugin for my xcode, and syntax highlighting is right there. Mine is official 10.10.3 and 6.3

**Comment by Kapeli** [comment] 2015-05-03 12:25
Seems to be an Xcode issue. I'll close this issue. If you have any more feedback please add a comment.

**Closed by Kapeli** 2015-05-03 12:25 UTC

**Comment by Skippern** [comment] 2015-05-03 12:43
Basically I cannot get it to work any more, it is reported to seeds, but probably won’t see a solution until next update. Have tried to de-activate and activate about anything without success.

**Comment by Skippern** [comment] 2015-05-07 17:44
Found a possible link with [mapcss-xcode-coloring](https://github.com/Skippern/mapcss-xcode-coloring/issues/1) - if anybody have knowledge how to solve it please let me know: problem seems isolated to this now.
